package utils.constants;

import java.util.HashMap;
import java.util.Map;

/**
 * This Class is used to store all the test constant variables.
 */
public class MessagingConstants {

    // -------------- KEY WORDS OTHER VALUES ------------------
    public static final String OTP = "111111";
    public static final String LAST_MODIFIED_ON = "Last modified on";
    public static final String DRAFT = "Draft";
    public static final String INDEX = "index";
    public static final String NUMERICAL_THREE = "3";
    public static final String KW_LKR = "LKR ";

    public static final String MESSAGES_UPLOAD = "MESSAGES_UPLOAD";
    public static final String MESSAGES_IMPORTANT_LABEL = "Important:";


    //--------------KEY WORDS TF ------------------
    public static final String COMPOSE_NEW_MESSAGE = "Compose New Message";
    public static final String ENTER_TO_WHOM_IT_SHOULD_BE_ADDRESSED = "Enter To whom it should be addressed";
    public static final String ENTER_MESSAGE = "Enter Message";
    public static final String ENTER_MESSAGE_SUBJECT = "Enter Message Subject";
    public static final String SELECT_ATTACHMENTS = "Select Attachments";
    public static final String ENTER_AMOUNT = "Enter Amount";
    public static final String ENTER_ACCOUNT_NUMBER = "Enter Account Number";
    public static final String ENTER_REMARKS = "Enter Remarks";
    public static final String SEARCH_MESSAGES = "Search Messages";
    public static final String OTHER_PURPOSE = "Other Purpose";
    public static final String START_TYPING = "Start typing...";

    // -------------- KEY WORDS RDO ------------------
    public static final String PERIOD = "period";
    public static final String AS_AT_DATE = "As at Date";
    public static final String AS_AT_DATE_LC = "as at date";
    public static final String SAMPATH = "Sampath";
    public static final String OTHER = "Other";

    // -------------- KEY WORDS Date ------------------
    public static final String FROM_DATE = "From Date";
    public static final String TO_DATE = "To Date";

    // -------------- KEY WORDS DD ------------------
    public static final String VISIBLE_TEXT = "visibletext";
    public static final String ALL_OPTIONS = "ALL_OPTIONS";

    // -------------- KEY WORDS BUTTON ------------------
    public static final String SEND = "Send";
    public static final String SAVE_AS_DRAFT = "Save as Draft";
    public static final String CONFIRM = "Confirm";
    public static final String TRASH = "Trash";
    public static final String ALL = "All";

    // -------------- SUBJECT DROPDOWN LIST ------------------

    public static final Map<String, String> SUBJECT_DROPDOWN = new HashMap<>();
    static {
        SUBJECT_DROPDOWN.put("KW_FUND_TRANSFER_DISPUTE", "Fund Transfer Dispute");
        SUBJECT_DROPDOWN.put("KW_BILL_PAYMENT_DISPUTE", "Bill Payment Dispute");
        SUBJECT_DROPDOWN.put("KW_CARD_CENTER", "Card Center");
        SUBJECT_DROPDOWN.put("KW_FUND_TRANSFER_REQUEST", "Fund Transfer Request");
        SUBJECT_DROPDOWN.put("KW_FIXED_DEPOSIT_INQUIRY", "Fixed Deposit Inquiry");
        SUBJECT_DROPDOWN.put("KW_BALANCE_CONFIRMATION_REQUEST", "Balance Confirmation Request");
        SUBJECT_DROPDOWN.put("KW_OTHER", "Other");
    }

    // -------------- PURPOSE DROPDOWN LIST ------------------
    public static final Map<String, String> PURPOSE_DROPDOWN = new HashMap<>();
    static {
        PURPOSE_DROPDOWN.put("KW_VISA", "Visa");
        PURPOSE_DROPDOWN.put("KW_TAX", "Tax");
        PURPOSE_DROPDOWN.put("KW_AUDIT", "Audit");
        PURPOSE_DROPDOWN.put("KW_OTHER", "Other");
    }
    public static final String[] PURPOSE_VALUES = {"Active", "Dormant"};

// -------------- KEY WORDS DATE PICKER ------------------

    public static final String TRANSACTION_DATE = "Transaction date";

    // -------------- BRANCH LIST ------------------
//    public static final Map<String, String> BRANCHES = new HashMap<>();
//    static {
//        BRANCHES.put("KW_Ahangama", "Ahangama");
//        BRANCHES.put("KW_Akkaraipattu", "Akkaraipattu");
//        BRANCHES.put("KW_Akuressa", "Akuressa");
//        BRANCHES.put("KW_Alawwa", "Alawwa");
//        BRANCHES.put("KW_Aluthgama", "Aluthgama");
//        BRANCHES.put("KW_Ambalangoda", "Ambalangoda");
//        BRANCHES.put("KW_Ambalantota", "Ambalantota");
//        BRANCHES.put("KW_Ampara", "Ampara");
//        BRANCHES.put("KW_Anamaduwa", "Anamaduwa");
//        BRANCHES.put("KW_AnuradhapuraNewTown", "Anuradhapura New Town");
//        BRANCHES.put("KW_AnuradhapuraSuper", "Anuradhapura Super");
//        BRANCHES.put("KW_Aralaganwila", "Aralaganwila");
//        BRANCHES.put("KW_Athurugiriya", "Athurugiriya");
//        BRANCHES.put("KW_Attidiya", "Attidiya");
//        BRANCHES.put("KW_Avissawella", "Avissawella");
//        BRANCHES.put("KW_Baddegama", "Baddegama");
//        BRANCHES.put("KW_Badulla", "Badulla");
//        BRANCHES.put("KW_Balangoda", "Balangoda");
//        BRANCHES.put("KW_Bambalapitiya", "Bambalapitiya");
//        BRANCHES.put("KW_Bandaragama", "Bandaragama");
//        BRANCHES.put("KW_Bandarawela", "Bandarawela");
//        BRANCHES.put("KW_Battaramulla", "Battaramulla");
//        BRANCHES.put("KW_Batticaloa", "Batticaloa");
//        BRANCHES.put("KW_BatticaloaIi", "Batticaloa Ii");
//        BRANCHES.put("KW_Beliatta", "Beliatta");
//        BRANCHES.put("KW_Bibile", "Bibile");
//        BRANCHES.put("KW_Boralesgamuwa", "Boralesgamuwa");
//        BRANCHES.put("KW_Borella", "Borella");
//        BRANCHES.put("KW_BorellaSuper", "Borella Super");
//        BRANCHES.put("KW_Buttala", "Buttala");
//        BRANCHES.put("KW_Chankanai", "Chankanai");
//        BRANCHES.put("KW_Chavakachcheri", "Chavakachcheri");
//        BRANCHES.put("KW_Chenkalady", "Chenkalady");
//        BRANCHES.put("KW_Chilaw", "Chilaw");
//        BRANCHES.put("KW_Chunnakam", "Chunnakam");
//        BRANCHES.put("KW_City", "City");
//        BRANCHES.put("KW_ColomboSuper", "Colombo Super");
//        BRANCHES.put("KW_Dambulla", "Dambulla");
//        BRANCHES.put("KW_Dankotuwa", "Dankotuwa");
//        BRANCHES.put("KW_Dehiattakandiya", "Dehiattakandiya");
//        BRANCHES.put("KW_Dehiwala", "Dehiwala");
//        BRANCHES.put("KW_Delgoda", "Delgoda");
//        BRANCHES.put("KW_Deniyaya", "Deniyaya");
//        BRANCHES.put("KW_Deraniyagala", "Deraniyagala");
//        BRANCHES.put("KW_Dickwella", "Dickwella");
//        BRANCHES.put("KW_Digana", "Digana");
//        BRANCHES.put("KW_Divulapitiya", "Divulapitiya");
//        BRANCHES.put("KW_Eheliyagoda", "Eheliyagoda");
//        BRANCHES.put("KW_Elpitiya", "Elpitiya");
//        BRANCHES.put("KW_Embilipitiya", "Embilipitiya");
//        BRANCHES.put("KW_Embuldeniya", "Embuldeniya");
//        BRANCHES.put("KW_Fort", "Fort");
//        BRANCHES.put("KW_Galewela", "Galewela");
//        BRANCHES.put("KW_GalleBazaar", "Galle Bazaar");
//        BRANCHES.put("KW_GalleSuper", "Galle Super");
//        BRANCHES.put("KW_Gampaha", "Gampaha");
//        BRANCHES.put("KW_GampahaSuper", "Gampaha Super");
//        BRANCHES.put("KW_Gampola", "Gampola");
//        BRANCHES.put("KW_Ganemulla", "Ganemulla");
//        BRANCHES.put("KW_Gangodawila", "Gangodawila");
//        BRANCHES.put("KW_Giriulla", "Giriulla");
//        BRANCHES.put("KW_Godakawela", "Godakawela");
//        BRANCHES.put("KW_GothatuwaNewTown", "Gothatuwa New Town");
//        BRANCHES.put("KW_Grandpass", "Grandpass");
//        BRANCHES.put("KW_GregoryRoad", "Gregory Road");
//        BRANCHES.put("KW_Habaraduwa", "Habaraduwa");
//        BRANCHES.put("KW_Hanwella", "Hanwella");
//        BRANCHES.put("KW_HarbourView", "Harbour View");
//        BRANCHES.put("KW_Hatton", "Hatton");
//        BRANCHES.put("KW_Headquarters", "Headquarters");
//        BRANCHES.put("KW_Heerassagala", "Heerassagala");
//        BRANCHES.put("KW_Hendala", "Hendala");
//        BRANCHES.put("KW_Hettipola", "Hettipola");
//        BRANCHES.put("KW_Hikkaduwa", "Hikkaduwa");
//        BRANCHES.put("KW_Hingurakgoda", "Hingurakgoda");
//        BRANCHES.put("KW_Homagama", "Homagama");
//        BRANCHES.put("KW_Horana", "Horana");
//        BRANCHES.put("KW_Ingiriya", "Ingiriya");
//        BRANCHES.put("KW_Jaela", "Ja-ela");
//        BRANCHES.put("KW_Jaffna", "Jaffna");
//        BRANCHES.put("KW_Kadawatha", "Kadawatha");
//        BRANCHES.put("KW_Kaduruwela", "Kaduruwela");
//        BRANCHES.put("KW_Kaduwela", "Kaduwela");
//        BRANCHES.put("KW_Kahatagasdigiliya", "Kahatagasdigiliya");
//        BRANCHES.put("KW_Kalawana", "Kalawana");
//        BRANCHES.put("KW_Kalmunai", "Kalmunai");
//        BRANCHES.put("KW_Kalutara", "Kalutara");
//        BRANCHES.put("KW_Kaluwanchikudy", "Kaluwanchikudy");
//        BRANCHES.put("KW_Kamburupitiya", "Kamburupitiya");
//        BRANCHES.put("KW_Kandana", "Kandana");
//        BRANCHES.put("KW_KandyCityCentre", "Kandy City Centre");
//        BRANCHES.put("KW_KandyMetro", "Kandy Metro");
//        BRANCHES.put("KW_KandySuper", "Kandy Super");
//        BRANCHES.put("KW_Kantale", "Kantale");
//        BRANCHES.put("KW_Karagampitiya", "Karagampitiya");
//        BRANCHES.put("KW_Karapitiya", "Karapitiya");
//        BRANCHES.put("KW_Kattankudy", "Kattankudy");
//        BRANCHES.put("KW_Katugastota", "Katugastota");
//        BRANCHES.put("KW_Kayts", "Kayts");
//        BRANCHES.put("KW_Kegalle", "Kegalle");
//        BRANCHES.put("KW_Kekirawa", "Kekirawa");
//        BRANCHES.put("KW_Kelaniya", "Kelaniya");
//        BRANCHES.put("KW_Kesbewa", "Kesbewa");
//        BRANCHES.put("KW_Keselwatta", "Keselwatta");
//        BRANCHES.put("KW_Killinochchi", "Killinochchi");
//        BRANCHES.put("KW_Kinniya", "Kinniya");
//        BRANCHES.put("KW_Kiribathgoda", "Kiribathgoda");
//        BRANCHES.put("KW_KiribathgodaSuper", "Kiribathgoda Super");
//        BRANCHES.put("KW_Kirindiwela", "Kirindiwela");
//        BRANCHES.put("KW_Kirulapone", "Kirulapone");
//        BRANCHES.put("KW_Kochchikade", "Kochchikade");
//        BRANCHES.put("KW_Kohuwala", "Kohuwala");
//        BRANCHES.put("KW_Kollupitiya", "Kollupitiya");
//        BRANCHES.put("KW_Kotahena", "Kotahena");
//        BRANCHES.put("KW_Kottawa", "Kottawa");
//        BRANCHES.put("KW_Kuliyapitiya", "Kuliyapitiya");
//        BRANCHES.put("KW_Kundasale", "Kundasale");
//        BRANCHES.put("KW_KurunegalaMetro", "Kurunegala Metro");
//        BRANCHES.put("KW_KurunegalaSuper", "Kurunegala Super");
//        BRANCHES.put("KW_Madampe", "Madampe");
//        BRANCHES.put("KW_Maharagama", "Maharagama");
//        BRANCHES.put("KW_MaharagamaSuper", "Maharagama Super");
//        BRANCHES.put("KW_Mahiyanganaya", "Mahiyanganaya");
//        BRANCHES.put("KW_Maho", "Maho");
//        BRANCHES.put("KW_MainStreet", "Main Street");
//        BRANCHES.put("KW_Makola", "Makola");
//        BRANCHES.put("KW_Malabe", "Malabe");
//        BRANCHES.put("KW_Mallavi", "Mallavi");
//        BRANCHES.put("KW_Manipay", "Manipay");
//        BRANCHES.put("KW_Mannar", "Mannar");
//        BRANCHES.put("KW_Maradana", "Maradana");
//        BRANCHES.put("KW_Marandagahamula", "Marandagahamula");
//        BRANCHES.put("KW_Marawila", "Marawila");
//        BRANCHES.put("KW_Matale", "Matale");
//        BRANCHES.put("KW_MataraBazaar", "Matara Bazaar");
//        BRANCHES.put("KW_MataraSuper", "Matara Super");
//        BRANCHES.put("KW_Mattegoda", "Mattegoda");
//        BRANCHES.put("KW_Matugama", "Matugama");
//        BRANCHES.put("KW_Mawanella", "Mawanella");
//        BRANCHES.put("KW_Mawathagama", "Mawathagama");
//        BRANCHES.put("KW_Menikhinna", "Menikhinna");
//        BRANCHES.put("KW_Middeniya", "Middeniya");
//        BRANCHES.put("KW_Minuwangoda", "Minuwangoda");
//        BRANCHES.put("KW_Mirigama", "Mirigama");
//        BRANCHES.put("KW_Monaragala", "Monaragala");
//        BRANCHES.put("KW_Moratumulla", "Moratumulla");
//        BRANCHES.put("KW_Moratuwa", "Moratuwa");
//        BRANCHES.put("KW_Morawaka", "Morawaka");
//        BRANCHES.put("KW_MountLavinia", "Mount Lavinia");
//        BRANCHES.put("KW_Muttur", "Muttur");
//        BRANCHES.put("KW_Mutwal", "Mutwal");
//        BRANCHES.put("KW_Narahenpita", "Narahenpita");
//        BRANCHES.put("KW_Narammala", "Narammala");
//        BRANCHES.put("KW_Nattandiya", "Nattandiya");
//        BRANCHES.put("KW_Nawala", "Nawala");
//        BRANCHES.put("KW_NawalaKoswatta", "Nawala Koswatta");
//        BRANCHES.put("KW_Nawalapitiya", "Nawalapitiya");
//        BRANCHES.put("KW_NawamMawatha", "Nawam Mawatha");
//        BRANCHES.put("KW_Negombo", "Negombo");
//        BRANCHES.put("KW_NegomboIi", "Negombo Ii");
//        BRANCHES.put("KW_Nelliady", "Nelliady");
//        BRANCHES.put("KW_Neluwa", "Neluwa");
//        BRANCHES.put("KW_Nikaweratiya", "Nikaweratiya");
//        BRANCHES.put("KW_Ninthavur", "Ninthavur");
//        BRANCHES.put("KW_Nittambuwa", "Nittambuwa");
//        BRANCHES.put("KW_Nochchiyagama", "Nochchiyagama");
//        BRANCHES.put("KW_Nugegoda", "Nugegoda");
//        BRANCHES.put("KW_Nuwaraeliya", "Nuwaraeliya");
//        BRANCHES.put("KW_Oddamavadi", "Oddamavadi");
//        BRANCHES.put("KW_OldMoorStreet", "Old Moor Street");
//        BRANCHES.put("KW_Orugodawatte", "Orugodawatte");
//        BRANCHES.put("KW_Padukka", "Padukka");
//        BRANCHES.put("KW_PanaduraWekada", "Panadura - Wekada");
//        BRANCHES.put("KW_PanaduraSuper", "Panadura Super");
//        BRANCHES.put("KW_Panchikawatte", "Panchikawatte");
//        BRANCHES.put("KW_Pannala", "Pannala");
//        BRANCHES.put("KW_Pannipitiya", "Pannipitiya");
//        BRANCHES.put("KW_Passara", "Passara");
//        BRANCHES.put("KW_Pelawatta", "Pelawatta");
//        BRANCHES.put("KW_Peliyagoda", "Peliyagoda");
//        BRANCHES.put("KW_Pelmadulla", "Pelmadulla");
//        BRANCHES.put("KW_Peradeniya", "Peradeniya");
//        BRANCHES.put("KW_Pettah", "Pettah");
//        BRANCHES.put("KW_Pilimatalawa", "Pilimatalawa");
//        BRANCHES.put("KW_Piliyandala", "Piliyandala");
//        BRANCHES.put("KW_Pitakotte", "Pitakotte");
//        BRANCHES.put("KW_PlatinumPlus", "Platinum Plus");
//        BRANCHES.put("KW_Polgahawela", "Polgahawela");
//        BRANCHES.put("KW_Poojapitiya", "Poojapitiya");
//        BRANCHES.put("KW_Pottuvil", "Pottuvil");
//        BRANCHES.put("KW_PrinceStreet", "Prince Street");
//        BRANCHES.put("KW_Pussellawa", "Pussellawa");
//        BRANCHES.put("KW_Puttalam", "Puttalam");
//        BRANCHES.put("KW_Ragama", "Ragama");
//        BRANCHES.put("KW_Rajagiriya", "Rajagiriya");
//        BRANCHES.put("KW_Rambukkana", "Rambukkana");
//        BRANCHES.put("KW_Ratmalana", "Ratmalana");
//        BRANCHES.put("KW_Ratnapura", "Ratnapura");
//        BRANCHES.put("KW_RatnapuraMetro", "Ratnapura Metro");
//        BRANCHES.put("KW_Rikillagaskada", "Rikillagaskada");
//        BRANCHES.put("KW_Ruwanwella", "Ruwanwella");
//        BRANCHES.put("KW_Sainthamaruthu", "Sainthamaruthu");
//        BRANCHES.put("KW_Seeduwa", "Seeduwa");
//        BRANCHES.put("KW_Sooriyawewa", "Sooriyawewa");
//        BRANCHES.put("KW_Talahena", "Talahena");
//        BRANCHES.put("KW_Talawakele", "Talawakele");
//        BRANCHES.put("KW_Tangalle", "Tangalle");
//        BRANCHES.put("KW_Thalawathugoda", "Thalawathugoda");
//        BRANCHES.put("KW_Thambuttegama", "Thambuttegama");
//        BRANCHES.put("KW_Thimbirigasyaya", "Thimbirigasyaya");
//        BRANCHES.put("KW_Thirunelveli", "Thirunelveli");
//        BRANCHES.put("KW_Tissamaharamaya", "Tissamaharamaya");
//        BRANCHES.put("KW_Trincomalee", "Trincomalee");
//        BRANCHES.put("KW_Vavuniya", "Vavuniya");
//        BRANCHES.put("KW_VavuniyaMetro", "Vavuniya Metro");
//        BRANCHES.put("KW_Veyangoda", "Veyangoda");
//        BRANCHES.put("KW_Wadduwa", "Wadduwa");
//        BRANCHES.put("KW_Warakapola", "Warakapola");
//        BRANCHES.put("KW_Wariyapola", "Wariyapola");
//        BRANCHES.put("KW_Wattala", "Wattala");
//        BRANCHES.put("KW_Wattegama", "Wattegama");
//        BRANCHES.put("KW_Weligama", "Weligama");
//        BRANCHES.put("KW_Welimada", "Welimada");
//        BRANCHES.put("KW_Wennappuwa", "Wennappuwa");
//        BRANCHES.put("KW_Wellampitiya", "Wellampitiya");
//        BRANCHES.put("KW_WellawatthaSuper", "Wellawattha Super");
//        BRANCHES.put("KW_Wellawaya", "Wellawaya");
//        BRANCHES.put("KW_WorldTradeCenter", "World Trade Center");
//        BRANCHES.put("KW_Yakkala", "Yakkala");
//    }

    public static final Map<String, String> BRANCHES = new HashMap<>();
    static {
        BRANCHES.put("KW_Ahangama", "AHANGAMA");
        BRANCHES.put("KW_Akkaraipattu", "AKKARAIPATTU");
        BRANCHES.put("KW_Akuressa", "AKURESSA");
        BRANCHES.put("KW_Alawwa", "ALAWWA");
        BRANCHES.put("KW_Aluthgama", "ALUTHGAMA");
        BRANCHES.put("KW_Ambalangoda", "AMBALANGODA");
        BRANCHES.put("KW_Ambalantota", "AMBALANTOTA");
        BRANCHES.put("KW_Ampara", "AMPARA");
        BRANCHES.put("KW_Anamaduwa", "ANAMADUWA");
        BRANCHES.put("KW_AnuradhapuraNewTown", "ANURADHAPURA NEW TOWN");
        BRANCHES.put("KW_AnuradhapuraSuper", "ANURADHAPURA SUPER");
        BRANCHES.put("KW_Aralaganwila", "ARALAGANWILA");
        BRANCHES.put("KW_Athurugiriya", "ATHURUGIRIYA");
        BRANCHES.put("KW_Attidiya", "ATTIDIYA");
        BRANCHES.put("KW_Avissawella", "AVISSAWELLA");
        BRANCHES.put("KW_Baddegama", "BADDEGAMA");
        BRANCHES.put("KW_Badulla", "BADULLA");
        BRANCHES.put("KW_Balangoda", "BALANGODA");
        BRANCHES.put("KW_Bambalapitiya", "BAMBALAPITIYA");
        BRANCHES.put("KW_Bandaragama", "BANDARAGAMA");
        BRANCHES.put("KW_Bandarawela", "BANDARAWELA");
        BRANCHES.put("KW_Battaramulla", "BATTARAMULLA");
        BRANCHES.put("KW_Batticaloa", "BATTICALOA");
        BRANCHES.put("KW_BatticaloaIi", "BATTICALOA II");
        BRANCHES.put("KW_Beliatta", "BELIATTA");
        BRANCHES.put("KW_Bibile", "BIBILE");
        BRANCHES.put("KW_Boralesgamuwa", "BORALESGAMUWA");
        BRANCHES.put("KW_Borella", "BORELLA");
        BRANCHES.put("KW_BorellaSuper", "BORELLA SUPER");
        BRANCHES.put("KW_Buttala", "BUTTALA");
        BRANCHES.put("KW_Chankanai", "CHANKANAI");
        BRANCHES.put("KW_Chavakachcheri", "CHAVAKACHCHERI");
        BRANCHES.put("KW_Chenkalady", "CHENKALADY");
        BRANCHES.put("KW_Chilaw", "CHILAW");
        BRANCHES.put("KW_Chunnakam", "CHUNNAKAM");
        BRANCHES.put("KW_City", "CITY");
        BRANCHES.put("KW_ColomboSuper", "COLOMBO SUPER");
        BRANCHES.put("KW_Dambulla", "DAMBULLA");
        BRANCHES.put("KW_Dankotuwa", "DANKOTUWA");
        BRANCHES.put("KW_Dehiattakandiya", "DEHIATTAKANDIYA");
        BRANCHES.put("KW_Dehiwala", "DEHIWALA");
        BRANCHES.put("KW_Delgoda", "DELGODA");
        BRANCHES.put("KW_Deniyaya", "DENIYAYA");
        BRANCHES.put("KW_Deraniyagala", "DERANIYAGALA");
        BRANCHES.put("KW_Dickwella", "DICKWELLA");
        BRANCHES.put("KW_Digana", "DIGANA");
        BRANCHES.put("KW_Divulapitiya", "DIVULAPITIYA");
        BRANCHES.put("KW_Eheliyagoda", "EHELIYAGODA");
        BRANCHES.put("KW_Elpitiya", "ELPITIYA");
        BRANCHES.put("KW_Embilipitiya", "EMBILIPITIYA");
        BRANCHES.put("KW_Embuldeniya", "EMBULDENIYA");
        BRANCHES.put("KW_Fort", "FORT");
        BRANCHES.put("KW_Galewela", "GALEWELA");
        BRANCHES.put("KW_GalleBazaar", "GALLE BAZAAR");
        BRANCHES.put("KW_GalleSuper", "GALLE SUPER");
        BRANCHES.put("KW_Gampaha", "GAMPAHA");
        BRANCHES.put("KW_GampahaSuper", "GAMPAHA SUPER");
        BRANCHES.put("KW_Gampola", "GAMPOLA");
        BRANCHES.put("KW_Ganemulla", "GANEMULLA");
        BRANCHES.put("KW_Gangodawila", "GANGODAWILA");
        BRANCHES.put("KW_Giriulla", "GIRIULLA");
        BRANCHES.put("KW_Godakawela", "GODAKAWELA");
        BRANCHES.put("KW_GothatuwaNewTown", "GOTHATUWA NEW TOWN");
        BRANCHES.put("KW_Grandpass", "GRANDPASS");
        BRANCHES.put("KW_GregoryRoad", "GREGORY ROAD");
        BRANCHES.put("KW_Habaraduwa", "HABARADUWA");
        BRANCHES.put("KW_Hanwella", "HANWELLA");
        BRANCHES.put("KW_HarbourView", "HARBOUR VIEW");
        BRANCHES.put("KW_Hatton", "HATTON");
        BRANCHES.put("KW_Headquarters", "HEADQUARTERS");
        BRANCHES.put("KW_Heerassagala", "HEERASSAGALA");
        BRANCHES.put("KW_Hendala", "HENDALA");
        BRANCHES.put("KW_Hettipola", "HETTIPOLA");
        BRANCHES.put("KW_Hikkaduwa", "HIKKADUWA");
        BRANCHES.put("KW_Hingurakgoda", "HINGURAKGODA");
        BRANCHES.put("KW_Homagama", "HOMAGAMA");
        BRANCHES.put("KW_Horana", "HORANA");
        BRANCHES.put("KW_Ingiriya", "INGIRIYA");
        BRANCHES.put("KW_Jaela", "JA-ELA");
        BRANCHES.put("KW_Jaffna", "JAFFNA");
        BRANCHES.put("KW_Kadawatha", "KADAWATHA");
        BRANCHES.put("KW_Kaduruwela", "KADURUWELA");
        BRANCHES.put("KW_Kaduwela", "KADUWELA");
        BRANCHES.put("KW_Kahatagasdigiliya", "KAHATAGASDIGILIYA");
        BRANCHES.put("KW_Kalawana", "KALAWANA");
        BRANCHES.put("KW_Kalmunai", "KALMUNAI");
        BRANCHES.put("KW_Kalutara", "KALUTARA");
        BRANCHES.put("KW_Kaluwanchikudy", "KALUWANCHIKUDY");
        BRANCHES.put("KW_Kamburupitiya", "KAMBURUPITIYA");
        BRANCHES.put("KW_Kandana", "KANDANA");
        BRANCHES.put("KW_KandyCityCentre", "KANDY CITY CENTRE");
        BRANCHES.put("KW_KandyMetro", "KANDY METRO");
        BRANCHES.put("KW_KandySuper", "KANDY SUPER");
        BRANCHES.put("KW_Kantale", "KANTALE");
        BRANCHES.put("KW_Karagampitiya", "KARAGAMPITIYA");
        BRANCHES.put("KW_Karapitiya", "KARAPITIYA");
        BRANCHES.put("KW_Kattankudy", "KATTANKUDY");
        BRANCHES.put("KW_Katugastota", "KATUGASTOTA");
        BRANCHES.put("KW_Kayts", "KAYTS");
        BRANCHES.put("KW_Kegalle", "KEGALLE");
        BRANCHES.put("KW_Kekirawa", "KEKIRAWA");
        BRANCHES.put("KW_Kelaniya", "KELANIYA");
        BRANCHES.put("KW_Kesbewa", "KESBEWA");
        BRANCHES.put("KW_Keselwatta", "KESELWATTA");
        BRANCHES.put("KW_Killinochchi", "KILLINOCHCHI");
        BRANCHES.put("KW_Kinniya", "KINNIYA");
        BRANCHES.put("KW_Kiribathgoda", "KIRIBATHGODA");
        BRANCHES.put("KW_KiribathgodaSuper", "KIRIBATHGODA SUPER");
        BRANCHES.put("KW_Kirindiwela", "KIRINDIWELA");
        BRANCHES.put("KW_Kirulapone", "KIRULAPONE");
        BRANCHES.put("KW_Kochchikade", "KOCHCHIKADE");
        BRANCHES.put("KW_Kohuwala", "KOHUWALA");
        BRANCHES.put("KW_Kollupitiya", "KOLLUPITIYA");
        BRANCHES.put("KW_Kotahena", "KOTAHENA");
        BRANCHES.put("KW_Kottawa", "KOTTAWA");
        BRANCHES.put("KW_Kuliyapitiya", "KULIYAPITIYA");
        BRANCHES.put("KW_Kundasale", "KUNDASALE");
        BRANCHES.put("KW_KurunegalaMetro", "KURUNEGALA METRO");
        BRANCHES.put("KW_KurunegalaSuper", "KURUNEGALA SUPER");
        BRANCHES.put("KW_Madampe", "MADAMPE");
        BRANCHES.put("KW_Maharagama", "MAHARAGAMA");
        BRANCHES.put("KW_MaharagamaSuper", "MAHARAGAMA SUPER");
        BRANCHES.put("KW_Mahiyanganaya", "MAHIYANGANAYA");
        BRANCHES.put("KW_Maho", "MAHO");
        BRANCHES.put("KW_MainStreet", "MAIN STREET");
        BRANCHES.put("KW_Makola", "MAKOLA");
        BRANCHES.put("KW_Malabe", "MALABE");
        BRANCHES.put("KW_Mallavi", "MALLAVI");
        BRANCHES.put("KW_Manipay", "MANIPAY");
        BRANCHES.put("KW_Mannar", "MANNAR");
        BRANCHES.put("KW_Maradana", "MARADANA");
        BRANCHES.put("KW_Marandagahamula", "MARANDAGAHAMULA");
        BRANCHES.put("KW_Marawila", "MARAWILA");
        BRANCHES.put("KW_Matale", "MATALE");
        BRANCHES.put("KW_MataraBazaar", "MATARA BAZAAR");
        BRANCHES.put("KW_MataraSuper", "MATARA SUPER");
        BRANCHES.put("KW_Mattegoda", "MATTEGODA");
        BRANCHES.put("KW_Matugama", "MATUGAMA");
        BRANCHES.put("KW_Mawanella", "MAWANELLA");
        BRANCHES.put("KW_Mawathagama", "MAWATHAGAMA");
        BRANCHES.put("KW_Menikhinna", "MENIKHINNA");
        BRANCHES.put("KW_Middeniya", "MIDDENIYA");
        BRANCHES.put("KW_Minuwangoda", "MINUWANGODA");
        BRANCHES.put("KW_Mirigama", "MIRIGAMA");
        BRANCHES.put("KW_Monaragala", "MONARAGALA");
        BRANCHES.put("KW_Moratumulla", "MORATUMULLA");
        BRANCHES.put("KW_Moratuwa", "MORATUWA");
        BRANCHES.put("KW_Morawaka", "MORAWAKA");
        BRANCHES.put("KW_MountLavinia", "MOUNT LAVINIA");
        BRANCHES.put("KW_Muttur", "MUTTUR");
        BRANCHES.put("KW_Mutwal", "MUTWAL");
        BRANCHES.put("KW_Narahenpita", "NARAHENPITA");
        BRANCHES.put("KW_Narammala", "NARAMMALA");
        BRANCHES.put("KW_Nattandiya", "NATTANDIYA");
        BRANCHES.put("KW_Nawala", "NAWALA");
        BRANCHES.put("KW_NawalaKoswatta", "NAWALA KOSWATTA");
        BRANCHES.put("KW_Nawalapitiya", "NAWALAPITIYA");
        BRANCHES.put("KW_NawamMawatha", "NAWAM MAWATHA");
        BRANCHES.put("KW_Negombo", "NEGOMBO");
        BRANCHES.put("KW_NegomboIi", "NEGOMBO II");
        BRANCHES.put("KW_Nelliady", "NELLIADY");
        BRANCHES.put("KW_Neluwa", "NELUWA");
        BRANCHES.put("KW_Nikaweratiya", "NIKAWERATIYA");
        BRANCHES.put("KW_Ninthavur", "NINTHAVUR");
        BRANCHES.put("KW_Nittambuwa", "NITTAMBUWA");
        BRANCHES.put("KW_Nochchiyagama", "NOCHCHIYAGAMA");
        BRANCHES.put("KW_Nugegoda", "NUGEGODA");
        BRANCHES.put("KW_Nuwaraeliya", "NUWARAELIYA");
        BRANCHES.put("KW_Oddamavadi", "ODDAMAVADI");
        BRANCHES.put("KW_OldMoorStreet", "OLD MOOR STREET");
        BRANCHES.put("KW_Orugodawatte", "ORUGODAWATTE");
        BRANCHES.put("KW_Padukka", "PADUKKA");
        BRANCHES.put("KW_PanaduraWekada", "PANADURA - WEKADA");
        BRANCHES.put("KW_PanaduraSuper", "PANADURA SUPER");
        BRANCHES.put("KW_Panchikawatte", "PANCHIKAWATTE");
        BRANCHES.put("KW_Pannala", "PANNALA");
        BRANCHES.put("KW_Pannipitiya", "PANNIPITIYA");
        BRANCHES.put("KW_Passara", "PASSARA");
        BRANCHES.put("KW_Pelawatta", "PELAWATTA");
        BRANCHES.put("KW_Peliyagoda", "PELIYAGODA");
        BRANCHES.put("KW_Pelmadulla", "PELMADULLA");
        BRANCHES.put("KW_Peradeniya", "PERADENIYA");
        BRANCHES.put("KW_Pettah", "PETTAH");
        BRANCHES.put("KW_Pilimatalawa", "PILIMATALAWA");
        BRANCHES.put("KW_Piliyandala", "PILIYANDALA");
        BRANCHES.put("KW_Pitakotte", "PITAKOTTE");
        BRANCHES.put("KW_PlatinumPlus", "PLATINUM PLUS");
        BRANCHES.put("KW_Polgahawela", "POLGAHAWELA");
        BRANCHES.put("KW_Poojapitiya", "POOJAPITIYA");
        BRANCHES.put("KW_Pottuvil", "POTTUVIL");
        BRANCHES.put("KW_PrinceStreet", "PRINCE STREET");
        BRANCHES.put("KW_Pussellawa", "PUSSELLAWA");
        BRANCHES.put("KW_Puttalam", "PUTTALAM");
        BRANCHES.put("KW_Ragama", "RAGAMA");
        BRANCHES.put("KW_Rajagiriya", "RAJAGIRIYA");
        BRANCHES.put("KW_Rambukkana", "RAMBUKKANA");
        BRANCHES.put("KW_Ratmalana", "RATMALANA");
        BRANCHES.put("KW_Ratnapura", "RATNAPURA");
        BRANCHES.put("KW_RatnapuraMetro", "RATNAPURA METRO");
        BRANCHES.put("KW_Rikillagaskada", "RIKILLAGASKADA");
        BRANCHES.put("KW_Ruwanwella", "RUWANWELLA");
        BRANCHES.put("KW_Sainthamaruthu", "SAINTHAMARUTHU");
        BRANCHES.put("KW_Seeduwa", "SEEDUWA");
        BRANCHES.put("KW_Sooriyawewa", "SOORIYAWEWA");
        BRANCHES.put("KW_Talahena", "TALAHENA");
        BRANCHES.put("KW_Talawakele", "TALAWAKELE");
        BRANCHES.put("KW_Tangalle", "TANGALLE");
        BRANCHES.put("KW_Thalawathugoda", "THALAWATHUGODA");
        BRANCHES.put("KW_Thambuttegama", "THAMBUTTEGAMA");
        BRANCHES.put("KW_Thimbirigasyaya", "THIMBIRIGASYAYA");
        BRANCHES.put("KW_Thirunelveli", "THIRUNELVELI");
        BRANCHES.put("KW_Tissamaharamaya", "TISSAMAHARAMAYA");
        BRANCHES.put("KW_Trincomalee", "TRINCOMALEE");
        BRANCHES.put("KW_Vavuniya", "VAVUNIYA");
        BRANCHES.put("KW_VavuniyaMetro", "VAVUNIYA METRO");
        BRANCHES.put("KW_Veyangoda", "VEYANGODA");
        BRANCHES.put("KW_Wadduwa", "WADDUWA");
        BRANCHES.put("KW_Warakapola", "WARAKAPOLA");
        BRANCHES.put("KW_Wariyapola", "WARIYAPOLA");
        BRANCHES.put("KW_Wattala", "WATTALA");
        BRANCHES.put("KW_Wattegama", "WATTEGAMA");
        BRANCHES.put("KW_Weligama", "WELIGAMA");
        BRANCHES.put("KW_Welimada", "WELIMADA");
        BRANCHES.put("KW_Wennappuwa", "WENNAPPUWA");
        BRANCHES.put("KW_Wellampitiya", "WELLAMPITIYA");
        BRANCHES.put("KW_WellawatthaSuper", "WELLAWATTHA SUPER");
        BRANCHES.put("KW_Wellawaya", "WELLAWAYA");
        BRANCHES.put("KW_WorldTradeCenter", "WORLD TRADE CENTER");
        BRANCHES.put("KW_Yakkala", "YAKKALA");
    }


    public static final Map<String, String> SUB_CATEGORY = new HashMap<>();
    static {
        SUB_CATEGORY.put("KW_CARD_ACTIVATION", "Card Activation");
        SUB_CATEGORY.put("KW_CREDIT_CARD_RENEWAL_RE_ISSUE_REPLACEMENT", "Credit Card Renewal/ Re-issue/ Replacement");
        SUB_CATEGORY.put("KW_ADD_CHANGE_SMS_ALERTS_NUMBER_ADDRESS_EMAIL_NAME", "Add/ Change SMS Alerts Number/ Address/ Email/ Name");
        SUB_CATEGORY.put("KW_REQUEST_LETTERS_LIMITS_CRIB_BALANCE_CANCELLATION_TRAVEL_INSURANCE", "Request Letters (Limits, CRIB, Balance, Cancellation)/ Travel Insurance");
        SUB_CATEGORY.put("KW_CARD_CANCELLATION", "Card Cancellation");
        SUB_CATEGORY.put("KW_TEMPORARY_DEACTIVATION", "Temporary Deactivation");
        SUB_CATEGORY.put("KW_DUE_DATE_CHANGE", "Due Date Change");
        SUB_CATEGORY.put("KW_GENERAL_REQUEST", "General Request");
        SUB_CATEGORY.put("KW_AUTOPAY_ACTIVATION_CHANGE_DEACTIVATION", "Autopay Activation/ Change/ Deactivation");
        SUB_CATEGORY.put("KW_FUND_TRANSFER_REQUEST", "Fund Transfer Request");
        SUB_CATEGORY.put("KW_LIMIT_ENHANCEMENT_CARD_UPGRADE", "Limit Enhancement/ Card Upgrade");
        SUB_CATEGORY.put("KW_UNSUCCESSFUL_POS_TRANSACTIONS", "Unsuccessful POS Transactions");
    }

}
